# Generated by Django 5.2.5 on 2025-08-15 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postapp", "0004_alter_post_options_alter_comment_reply"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="reply",
        ),
        migrations.AddField(
            model_name="comment",
            name="image",
            field=models.FileField(
                default="comment_image/user.png", upload_to="comment_image"
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="postapp.comment",
            ),
            preserve_default=False,
        ),
    ]
