# Generated by Django 5.2.5 on 2025-08-15 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postapp", "0005_remove_comment_reply_comment_image_comment_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="postapp.comment",
            ),
        ),
    ]
