# Generated by Django 5.2.5 on 2025-08-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postapp", "0006_alter_comment_parent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="tasg",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="tags", to="postapp.tag"
            ),
        ),
    ]
