# Generated by Django 5.2.5 on 2025-08-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postapp", "0007_tag_post_tasg"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="tasg",
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="tags", to="postapp.tag"
            ),
        ),
    ]
