# Generated by Django 5.2.5 on 2025-08-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postapp", "0008_remove_post_tasg_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="postapp.tag"
            ),
        ),
    ]
